<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>../../.godot/config-transaction-tests/obj/</BaseIntermediateOutputPath>
    <BaseOutputPath>../../.godot/config-transaction-tests/bin/</BaseOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);CONFIG_TRANSACTION_TESTS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="../../scripts/framework/config/converter/ConfigOutputTransaction.cs" Link="ConfigOutputTransaction.cs" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
